[package]
name = "HAL-Project"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2"
avr-device = { version = "0.5.4", features = ["atmega328p", "rt"] }

[profile.release]
panic = "abort"
