[package]
name = "HAL-Project"
version = "0.1.0"
edition = "2021"

[dependencies]
arduino-hal = { git = "https://github.com/Rahix/avr-hal", branch = "main", features = ["arduino-uno"] }
panic-halt = "0.2"


[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
