[target.avr-atmega328p]
linker = "avr-gcc"
rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-nodefaultlibs",
    "-C", "link-arg=-Wl,--strip-all",
    "-C", "link-arg=-Wl,--no-eh-frame-hdr" 
]
